# Introduction to pandas

# key data structures in pandas
- series
- dataframe

In [7]:
import pandas as pd

In [12]:
s = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])

In [13]:
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

# dataframe

In [15]:
df = pd.DataFrame({"names" : ["harry","rohan","ps"],  "marks": [80,90,100]})

In [16]:
df

   names  marks
0  harry     80
1  rohan     90
2     ps    100

In [18]:
df=pd.read_csv("dim_date.csv")

In [19]:
df

         date  mmm yy week no  day_type
0   01-May-22  May 22    W 19   weekend
1   02-May-22  May 22    W 19  weekeday
2   03-May-22  May 22    W 19  weekeday
3   04-May-22  May 22    W 19  weekeday
4   05-May-22  May 22    W 19  weekeday
..        ...     ...     ...       ...
87  27-Jul-22  Jul 22    W 31  weekeday
88  28-Jul-22  Jul 22    W 31  weekeday
89  29-Jul-22  Jul 22    W 31  weekeday
90  30-Jul-22  Jul 22    W 31   weekend
91  31-Jul-22  Jul 22    W 32   weekend

[92 rows x 4 columns]

In [22]:
df.head()

        date  mmm yy week no  day_type
0  01-May-22  May 22    W 19   weekend
1  02-May-22  May 22    W 19  weekeday
2  03-May-22  May 22    W 19  weekeday
3  04-May-22  May 22    W 19  weekeday
4  05-May-22  May 22    W 19  weekeday

In [23]:
df.tail()

         date  mmm yy week no  day_type
87  27-Jul-22  Jul 22    W 31  weekeday
88  28-Jul-22  Jul 22    W 31  weekeday
89  29-Jul-22  Jul 22    W 31  weekeday
90  30-Jul-22  Jul 22    W 31   weekend
91  31-Jul-22  Jul 22    W 32   weekend

In [24]:
df.describe()

             date  mmm yy week no  day_type
count          92      92      92        92
unique         92       3      14         2
top     01-May-22  May 22    W 19  weekeday
freq            1      31       7        65

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      92 non-null     object
 1   mmm yy    92 non-null     object
 2   week no   92 non-null     object
 3   day_type  92 non-null     object
dtypes: object(4)
memory usage: 3.0+ KB

# Data Selection

In [27]:
df["date"]

0     01-May-22
1     02-May-22
2     03-May-22
3     04-May-22
4     05-May-22
        ...
87    27-Jul-22
88    28-Jul-22
89    29-Jul-22
90    30-Jul-22
91    31-Jul-22
Name: date, Length: 92, dtype: object

In [28]:
type(df["date"])

pandas.core.series.Series

In [31]:
df[["date","mmm yy"]]

         date  mmm yy
0   01-May-22  May 22
1   02-May-22  May 22
2   03-May-22  May 22
3   04-May-22  May 22
4   05-May-22  May 22
..        ...     ...
87  27-Jul-22  Jul 22
88  28-Jul-22  Jul 22
89  29-Jul-22  Jul 22
90  30-Jul-22  Jul 22
91  31-Jul-22  Jul 22

[92 rows x 2 columns]

In [37]:
df.iloc[1]

date        02-May-22
mmm yy         May 22
week no          W 19
day_type     weekeday
Name: 1, dtype: object

In [38]:
type(df.iloc[1])

pandas.core.series.Series