# Introduction to pandas

# key data structures in pandas
- series
- dataframe

In [1]:
import pandas as pd

In [2]:
s = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])

In [3]:
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

# dataframe

In [4]:
df = pd.DataFrame({"names" : ["harry","rohan","ps"],  "marks": [80,90,100]})

In [5]:
df

   names  marks
0  harry     80
1  rohan     90
2     ps    100

In [6]:
df=pd.read_csv("Details.csv")

In [7]:
df

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card
...,...,...,...,...,...,...,...
1495,B-25700,7,-3,2,Clothing,Hankerchief,COD
1496,B-25757,3151,-35,7,Clothing,Trousers,EMI
1497,B-25973,4141,1698,13,Electronics,Printers,COD
1498,B-25698,7,-2,1,Clothing,Hankerchief,COD
1499,B-25993,4363,305,5,Furniture,Tables,EMI

In [8]:
df.head()

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card

In [9]:
df.tail()

     Order ID  Amount  Profit  Quantity     Category Sub-Category PaymentMode
1495  B-25700       7      -3         2     Clothing  Hankerchief         COD
1496  B-25757    3151     -35         7     Clothing     Trousers         EMI
1497  B-25973    4141    1698        13  Electronics     Printers         COD
1498  B-25698       7      -2         1     Clothing  Hankerchief         COD
1499  B-25993    4363     305         5    Furniture       Tables         EMI

In [10]:
df.describe()

            Amount      Profit     Quantity
count  1500.000000  1500.00000  1500.000000
mean    291.847333    24.64200     3.743333
std     461.924620   168.55881     2.184942
min       4.000000 -1981.00000     1.000000
25%      47.750000   -12.00000     2.000000
50%     122.000000     8.00000     3.000000
75%     326.250000    38.00000     5.000000
max    5729.000000  1864.00000    14.000000

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      1500 non-null   object
 1   Amount        1500 non-null   int64
 2   Profit        1500 non-null   int64
 3   Quantity      1500 non-null   int64
 4   Category      1500 non-null   object
 5   Sub-Category  1500 non-null   object
 6   PaymentMode   1500 non-null   object
dtypes: int64(3), object(4)
memory usage: 82.2+ KB

# Data Selection

In [13]:
df["Amount"]

0       1096
1       5729
2       2927
3       2847
4       2617
        ...
1495       7
1496    3151
1497    4141
1498       7
1499    4363
Name: Amount, Length: 1500, dtype: int64

In [14]:
type(df["Amount"])

pandas.core.series.Series

In [16]:
df[["Amount","Order ID"]]

      Amount Order ID
0       1096  B-25681
1       5729  B-26055
2       2927  B-25955
3       2847  B-26093
4       2617  B-25602
...      ...      ...
1495       7  B-25700
1496    3151  B-25757
1497    4141  B-25973
1498       7  B-25698
1499    4363  B-25993

[1500 rows x 2 columns]

In [17]:
df.iloc[1]

Order ID          B-26055
Amount               5729
Profit                 64
Quantity               14
Category        Furniture
Sub-Category       Chairs
PaymentMode           EMI
Name: 1, dtype: object

In [18]:
type(df.iloc[1])

pandas.core.series.Series

In [19]:
df2=pd.read_csv("details_new.csv")

In [20]:
df2

     Order ID  Amount  Profit  Quantity     Category Sub-Category  PaymentMode
0     B-25681  1096.0   658.0       7.0  Electronics          NaN          COD
1     B-26055  5729.0    64.0       NaN    Furniture       Chairs          EMI
2     B-25955  2927.0   146.0       8.0          NaN    Bookcases          EMI
3     B-26093  2847.0   712.0       8.0  Electronics     Printers  Credit Card
4     B-25602  2617.0  1151.0       4.0  Electronics       Phones  Credit Card
...       ...     ...     ...       ...          ...          ...          ...
1495  B-25700     7.0    -3.0       2.0     Clothing  Hankerchief          COD
1496  B-25757  3151.0   -35.0       7.0     Clothing     Trousers          EMI
1497  B-25973  4141.0  1698.0      13.0  Electronics     Printers          COD
1498  B-25698     7.0    -2.0       1.0     Clothing  Hankerchief          COD
1499  B-25993  4363.0   305.0       5.0    Furniture       Tables          EMI

[1500 rows x 7 columns]

In [21]:
df2.dropna()

     Order ID  Amount  Profit  Quantity     Category Sub-Category  PaymentMode
3     B-26093  2847.0   712.0       8.0  Electronics     Printers  Credit Card
4     B-25602  2617.0  1151.0       4.0  Electronics       Phones  Credit Card
5     B-25881  2244.0   247.0       4.0     Clothing     Trousers  Credit Card
7     B-25687   387.0  -213.0       5.0     Clothing        Saree          UPI
8     B-25643    50.0   -44.0       2.0     Clothing  Hankerchief          UPI
...       ...     ...     ...       ...          ...          ...          ...
1495  B-25700     7.0    -3.0       2.0     Clothing  Hankerchief          COD
1496  B-25757  3151.0   -35.0       7.0     Clothing     Trousers          EMI
1497  B-25973  4141.0  1698.0      13.0  Electronics     Printers          COD
1498  B-25698     7.0    -2.0       1.0     Clothing  Hankerchief          COD
1499  B-25993  4363.0   305.0       5.0    Furniture       Tables          EMI

[1490 rows x 7 columns]

In [22]:
df2.fillna(0)

     Order ID  Amount  Profit  Quantity     Category Sub-Category  PaymentMode
0     B-25681  1096.0   658.0       7.0  Electronics            0          COD
1     B-26055  5729.0    64.0       0.0    Furniture       Chairs          EMI
2     B-25955  2927.0   146.0       8.0            0    Bookcases          EMI
3     B-26093  2847.0   712.0       8.0  Electronics     Printers  Credit Card
4     B-25602  2617.0  1151.0       4.0  Electronics       Phones  Credit Card
...       ...     ...     ...       ...          ...          ...          ...
1495  B-25700     7.0    -3.0       2.0     Clothing  Hankerchief          COD
1496  B-25757  3151.0   -35.0       7.0     Clothing     Trousers          EMI
1497  B-25973  4141.0  1698.0      13.0  Electronics     Printers          COD
1498  B-25698     7.0    -2.0       1.0     Clothing  Hankerchief          COD
1499  B-25993  4363.0   305.0       5.0    Furniture       Tables          EMI

[1500 rows x 7 columns]

In [24]:
df2.rename(columns={"Quantity":"matra"},inplace=True)

In [25]:
df2.describe()

            Amount       Profit        matra
count  1499.000000  1499.000000  1497.000000
mean    290.624416    25.252835     3.735471
std     459.643348   166.946057     2.170729
min       4.000000 -1981.000000     1.000000
25%      47.500000   -12.000000     2.000000
50%     122.000000     8.000000     3.000000
75%     325.500000    38.000000     5.000000
max    5729.000000  1864.000000    14.000000

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      1500 non-null   object
 1   Amount        1500 non-null   int64
 2   Profit        1500 non-null   int64
 3   Quantity      1500 non-null   int64
 4   Category      1500 non-null   object
 5   Sub-Category  1500 non-null   object
 6   PaymentMode   1500 non-null   object
dtypes: int64(3), object(4)
memory usage: 82.2+ KB

In [28]:
df2.describe()

            Amount       Profit        matra
count  1499.000000  1499.000000  1497.000000
mean    290.624416    25.252835     3.735471
std     459.643348   166.946057     2.170729
min       4.000000 -1981.000000     1.000000
25%      47.500000   -12.000000     2.000000
50%     122.000000     8.000000     3.000000
75%     325.500000    38.000000     5.000000
max    5729.000000  1864.000000    14.000000

In [29]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      1500 non-null   object
 1   Amount        1499 non-null   float64
 2   Profit        1499 non-null   float64
 3   matra         1497 non-null   float64
 4   Category      1498 non-null   object
 5   Sub-Category  1498 non-null   object
 6   PaymentMode   1499 non-null   object
dtypes: float64(3), object(4)
memory usage: 82.2+ KB

In [36]:
df

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card
...,...,...,...,...,...,...,...
1495,B-25700,7,-3,2,Clothing,Hankerchief,COD
1496,B-25757,3151,-35,7,Clothing,Trousers,EMI
1497,B-25973,4141,1698,13,Electronics,Printers,COD
1498,B-25698,7,-2,1,Clothing,Hankerchief,COD
1499,B-25993,4363,305,5,Furniture,Tables,EMI

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      1500 non-null   object
 1   Amount        1500 non-null   int64
 2   Profit        1500 non-null   int64
 3   Quantity      1500 non-null   int64
 4   Category      1500 non-null   object
 5   Sub-Category  1500 non-null   object
 6   PaymentMode   1500 non-null   object
dtypes: int64(3), object(4)
memory usage: 82.2+ KB

In [38]:
df["Amount"]=df["Amount"].astype(float)

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      1500 non-null   object
 1   Amount        1500 non-null   float64
 2   Profit        1500 non-null   int64
 3   Quantity      1500 non-null   int64
 4   Category      1500 non-null   object
 5   Sub-Category  1500 non-null   object
 6   PaymentMode   1500 non-null   object
dtypes: float64(1), int64(2), object(4)
memory usage: 82.2+ KB

In [41]:
df

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096.0,658,7,Electronics,Electronic Games,COD
1,B-26055,5729.0,64,14,Furniture,Chairs,EMI
2,B-25955,2927.0,146,8,Furniture,Bookcases,EMI
3,B-26093,2847.0,712,8,Electronics,Printers,Credit Card
4,B-25602,2617.0,1151,4,Electronics,Phones,Credit Card
...,...,...,...,...,...,...,...
1495,B-25700,7.0,-3,2,Clothing,Hankerchief,COD
1496,B-25757,3151.0,-35,7,Clothing,Trousers,EMI
1497,B-25973,4141.0,1698,13,Electronics,Printers,COD
1498,B-25698,7.0,-2,1,Clothing,Hankerchief,COD
1499,B-25993,4363.0,305,5,Furniture,Tables,EMI

In [44]:
df["Quantity"]=df["Quantity"].astype(str)

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      1500 non-null   object
 1   Amount        1500 non-null   float64
 2   Profit        1500 non-null   object
 3   Quantity      1500 non-null   object
 4   Category      1500 non-null   object
 5   Sub-Category  1500 non-null   object
 6   PaymentMode   1500 non-null   object
dtypes: float64(1), object(6)
memory usage: 82.2+ KB

In [47]:
df["Quantity"][0]

'7'

In [48]:
len(df)

1500

In [49]:
df["zeroes"]=[i for i in range(len(df))]

In [50]:
df

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode,zeroes
0,B-25681,1096.0,658,7,Electronics,Electronic Games,COD,0
1,B-26055,5729.0,64,14,Furniture,Chairs,EMI,1
2,B-25955,2927.0,146,8,Furniture,Bookcases,EMI,2
3,B-26093,2847.0,712,8,Electronics,Printers,Credit Card,3
4,B-25602,2617.0,1151,4,Electronics,Phones,Credit Card,4
...,...,...,...,...,...,...,...,...
1495,B-25700,7.0,-3,2,Clothing,Hankerchief,COD,1495
1496,B-25757,3151.0,-35,7,Clothing,Trousers,EMI,1496
1497,B-25973,4141.0,1698,13,Electronics,Printers,COD,1497
1498,B-25698,7.0,-2,1,Clothing,Hankerchief,COD,1498
1499,B-25993,4363.0,305,5,Furniture,Tables,EMI,1499

In [54]:
df["Quantity"]=df["Quantity"].astype(int)

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      1500 non-null   object
 1   Amount        1500 non-null   float64
 2   Profit        1500 non-null   object
 3   Quantity      1500 non-null   int64
 4   Category      1500 non-null   object
 5   Sub-Category  1500 non-null   object
 6   PaymentMode   1500 non-null   object
 7   zeroes        1500 non-null   int64
 8   exponent      0 non-null      object
dtypes: float64(1), int64(2), object(6)
memory usage: 105.6+ KB

In [60]:
def power(a):
    return a*a
df["exponent"]=df["Quantity"].apply(power)

In [61]:
df

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode,zeroes,exponent
0,B-25681,1096.0,658,7,Electronics,Electronic Games,COD,0,49
1,B-26055,5729.0,64,14,Furniture,Chairs,EMI,1,196
2,B-25955,2927.0,146,8,Furniture,Bookcases,EMI,2,64
3,B-26093,2847.0,712,8,Electronics,Printers,Credit Card,3,64
4,B-25602,2617.0,1151,4,Electronics,Phones,Credit Card,4,16
...,...,...,...,...,...,...,...,...,...
1495,B-25700,7.0,-3,2,Clothing,Hankerchief,COD,1495,4
1496,B-25757,3151.0,-35,7,Clothing,Trousers,EMI,1496,49
1497,B-25973,4141.0,1698,13,Electronics,Printers,COD,1497,169
1498,B-25698,7.0,-2,1,Clothing,Hankerchief,COD,1498,1
1499,B-25993,4363.0,305,5,Furniture,Tables,EMI,1499,25

In [63]:
df.to_csv("C:\projects\pandas\export.csv",index=False)

In [64]:
df3=pd.DataFrame({"name":["ps","ms","ss"],"age":[20,22,45]})

In [65]:
df3

  name  age
0   ps   20
1   ms   22
2   ss   45

In [76]:
df4=pd.DataFrame({"name":["ps","ms","ss","hari"],"no":[10,11,23,44]})

In [77]:
df4

   name  no
0    ps  10
1    ms  11
2    ss  23
3  hari  44

In [79]:
pd.merge(df3,df4,on="name")

  name  age  no
0   ps   20  10
1   ms   22  11
2   ss   45  23